// Emoji shortcode mapping
const emojiMap = {
  // Smileys & Emotion
  smile: '😄',
  grinning: '😀',
  grin: '😁',
  joy: '😂',
  rofl: '🤣',
  smiley: '😃',
  sweat_smile: '😅',
  laughing: '😆',
  wink: '😉',
  blush: '😊',
  yum: '😋',
  sunglasses: '😎',
  heart_eyes: '😍',
  kissing_heart: '😘',
  kissing: '😗',
  relaxed: '☺️',
  slight_smile: '🙂',
  hugging: '🤗',
  thinking: '🤔',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  rolling_eyes: '🙄',
  smirk: '😏',
  persevere: '😣',
  disappointed: '😞',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  cry: '😢',
  sob: '😭',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  cold_sweat: '😰',
  disappointed_relieved: '😥',
  hushed: '😯',
  astonished: '😲',
  flushed: '😳',
  scream: '😱',
  sleeping: '😴',
  dizzy_face: '😵',
  confused: '😕',
  worried: '😟',
  angry: '😠',
  rage: '😡',
  triumph: '😤',
  pensive: '😔',
  unamused: '😒',
  mask: '😷',
  nerd: '🤓',
  innocent: '😇',
  imp: '😈',
  alien: '👽',
  robot: '🤖',
  clown: '🤡',
  poop: '💩',
  ghost: '👻',
  skull: '💀',
  skull_crossbones: '☠️',

  // Gestures & Body
  wave: '👋',
  raised_hand: '✋',
  ok_hand: '👌',
  thumbsup: '👍',
  '+1': '👍',
  thumbsdown: '👎',
  '-1': '👎',
  clap: '👏',
  pray: '🙏',
  muscle: '💪',
  point_up: '☝️',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  middle_finger: '🖕',
  raised_hands: '🙌',
  fist: '✊',
  punch: '👊',
  v: '✌️',
  metal: '🤘',
  call_me: '🤙',
  hand_splayed: '🖐️',
  writing_hand: '✍️',
  eyes: '👀',
  eye: '👁️',
  brain: '🧠',

  // Hearts & Love
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  broken_heart: '💔',
  sparkling_heart: '💖',
  heartbeat: '💓',
  heartpulse: '💗',
  two_hearts: '💕',
  gift_heart: '💝',
  cupid: '💘',
  kiss: '💋',

  // Objects & Symbols
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  zap: '⚡',
  fire: '🔥',
  boom: '💥',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  trophy: '🏆',
  medal: '🏅',
  crown: '👑',
  gem: '💎',
  moneybag: '💰',
  money_with_wings: '💸',
  bulb: '💡',
  bell: '🔔',
  bookmark: '🔖',
  link: '🔗',
  pushpin: '📌',
  paperclip: '📎',
  scissors: '✂️',
  pencil: '✏️',
  pen: '🖊️',
  memo: '📝',
  book: '📖',
  books: '📚',
  notebook: '📓',
  calendar: '📅',
  chart: '📊',
  chart_up: '📈',
  chart_down: '📉',
  clipboard: '📋',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  hammer: '🔨',
  wrench: '🔧',
  gear: '⚙️',
  magnet: '🧲',
  microscope: '🔬',
  telescope: '🔭',

  // Tech & Devices
  computer: '💻',
  desktop: '🖥️',
  keyboard: '⌨️',
  mouse: '🖱️',
  phone: '📱',
  email: '📧',
  inbox: '📥',
  outbox: '📤',
  package: '📦',
  floppy_disk: '💾',
  cd: '💿',
  dvd: '📀',
  camera: '📷',
  video_camera: '📹',
  tv: '📺',
  radio: '📻',
  speaker: '🔊',
  mute: '🔇',
  battery: '🔋',
  electric_plug: '🔌',

  // Nature & Weather
  sun: '☀️',
  moon: '🌙',
  cloud: '☁️',
  rain: '🌧️',
  thunder: '⛈️',
  snow: '❄️',
  rainbow: '🌈',
  umbrella: '☂️',
  ocean: '🌊',
  earth: '🌍',
  world: '🌎',
  globe: '🌐',
  tree: '🌳',
  palm_tree: '🌴',
  cactus: '🌵',
  flower: '🌸',
  rose: '🌹',
  sunflower: '🌻',
  seedling: '🌱',
  leaf: '🍃',
  fallen_leaf: '🍂',
  maple_leaf: '🍁',

  // Animals
  dog: '🐕',
  cat: '🐈',
  mouse_face: '🐭',
  rabbit: '🐰',
  fox: '🦊',
  bear: '🐻',
  panda: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey: '🐒',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  eagle: '🦅',
  owl: '🦉',
  duck: '🦆',
  butterfly: '🦋',
  bee: '🐝',
  bug: '🐛',
  snail: '🐌',
  turtle: '🐢',
  snake: '🐍',
  dragon: '🐉',
  whale: '🐋',
  dolphin: '🐬',
  fish: '🐟',
  octopus: '🐙',
  crab: '🦀',
  unicorn: '🦄',

  // Food & Drink
  apple: '🍎',
  green_apple: '🍏',
  banana: '🍌',
  orange: '🍊',
  lemon: '🍋',
  grapes: '🍇',
  watermelon: '🍉',
  strawberry: '🍓',
  peach: '🍑',
  cherry: '🍒',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  burrito: '🌯',
  popcorn: '🍿',
  ice_cream: '🍨',
  cake: '🎂',
  cookie: '🍪',
  chocolate: '🍫',
  candy: '🍬',
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  wine: '🍷',
  cocktail: '🍸',
  tropical_drink: '🍹',

  // Status & Indicators
  check: '✅',
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  x: '❌',
  cross_mark: '❌',
  exclamation: '❗',
  question: '❓',
  warning: '⚠️',
  no_entry: '⛔',
  stop_sign: '🛑',
  info: 'ℹ️',
  construction: '🚧',
  recycle: '♻️',
  sos: '🆘',
  new: '🆕',
  free: '🆓',
  up: '🆙',
  cool: '🆒',
  ok: '🆗',

  // Arrows & Directions
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_left: '⬅️',
  arrow_right: '➡️',
  arrow_upper_right: '↗️',
  arrow_lower_right: '↘️',
  arrow_lower_left: '↙️',
  arrow_upper_left: '↖️',
  arrows_counterclockwise: '🔄',
  back: '🔙',
  end: '🔚',
  soon: '🔜',
  top: '🔝',

  // Misc
  rocket: '🚀',
  airplane: '✈️',
  car: '🚗',
  bus: '🚌',
  train: '🚆',
  ship: '🚢',
  anchor: '⚓',
  house: '🏠',
  office: '🏢',
  hospital: '🏥',
  school: '🏫',
  church: '⛪',
  tent: '⛺',
  mountain: '⛰️',
  volcano: '🌋',
  camping: '🏕️',
  beach: '🏖️',
  island: '🏝️',
  sunrise: '🌅',
  sunset: '🌇',
  night: '🌃',
  milky_way: '🌌',

  // Special
  vomit: '🤮',
  nauseated: '🤢',
  sick: '🤒',
  hot_face: '🥵',
  cold_face: '🥶',
  party: '🥳',
  partying_face: '🥳',
  shushing: '🤫',
  lying: '🤥',
  exploding_head: '🤯',
  cowboy: '🤠',
  nerd_face: '🤓',
  monocle: '🧐',
  pleading: '🥺',
  yawning: '🥱',
};

// Replace emoji shortcodes with actual emojis
function replaceEmojis(text) {
  return text.replace(/:([a-zA-Z0-9_+-]+):/g, (match, code) => {
    const emoji = emojiMap[code.toLowerCase()];
    return emoji || match;
  });
}

// Export for use in browser
window.replaceEmojis = replaceEmojis;
window.emojiMap = emojiMap;
